# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

src = Path("src")

a = Analysis(
    [str(src / "wct" / "main.py")],
    pathex=[str(src)],
    binaries=[],
    datas=[
        (str(src / "wct" / "db" / "schema.sql"), "wct/db"),
    ],
    hiddenimports=[
        "wct",
        "wct.main",
        "wct.app",
        "wct.config.paths",
        "wct.config.settings",
        "wct.core.i18n",
        "wct.core.event_bus",
        "wct.core.commands",
        "wct.core.command_palette",
        "wct.core.glyphs",
        "wct.core.preferences",
        "wct.core.usage",
        "wct.core.sysinfo",
        "wct.core.diagnostics",
        "wct.core.build_info",
        "wct.core.changelog",
        "wct.core.markdown_lite",
        "wct.core.plugins",
        "wct.core.hotkeys",
        "wct.core.updater",
        "wct.core.notifications",
        "wct.core.scheduler",
        "wct.core.tray",
        "wct.core.autostart",
        "wct.core.backup",
        "wct.core.exporter",
        "wct.core.format",
        "wct.core.text_search",
        "wct.core.throttle",
        "wct.core.stats",
        "wct.db.database",
        "wct.db.repositories",
        "wct.db.migrations",
        "wct.modules.network.service",
        "wct.modules.network.monitor",
        "wct.modules.network.firewall_adapter",
        "wct.modules.network.bandwidth_service",
        "wct.modules.network.bandwidth",
        "wct.modules.network.dns_cache",
        "wct.modules.network.dns_resolver",
        "wct.modules.network.geoip",
        "wct.modules.network.port_registry",
        "wct.modules.network.risk",
        "wct.modules.network.risk_scorer",
        "wct.modules.files.service",
        "wct.modules.files.scanner",
        "wct.modules.files.actions",
        "wct.modules.files.rule_engine",
        "wct.modules.files.templates",
        "wct.modules.files.monitor",
        "wct.modules.files.dedupe",
        "wct.modules.files.dedupe_pro",
        "wct.modules.files.size_analyzer",
        "wct.ui.theme",
        "wct.ui.main_window",
        "wct.ui.pages.dashboard_page",
        "wct.ui.pages.network_page",
        "wct.ui.pages.firewall_rules_page",
        "wct.ui.pages.bandwidth_page",
        "wct.ui.pages.risk_page",
        "wct.ui.pages.trust_page",
        "wct.ui.pages.downloads_page",
        "wct.ui.pages.file_rules_page",
        "wct.ui.pages.duplicates_page",
        "wct.ui.pages.disk_hogs_page",
        "wct.ui.pages.quarantine_page",
        "wct.ui.pages.history_page",
        "wct.ui.pages.notifications_page",
        "wct.ui.pages.settings_page",
        "wct.ui.pages.about_page",
        "wct.ui.pages.process_inspector_page",
        "wct.ui.pages.task_manager_page",
        "wct.ui.pages.scheduler_page",
        "wct.ui.pages.welcome_screen",
        "wct.ui.widgets.stat_card",
        "wct.ui.widgets.sparkline",
        "wct.ui.widgets.search_box",
        "wct.ui.widgets.progress_chip",
        "wct.ui.widgets.command_palette",
        "wct.shared.models",
        "psutil",
        "watchdog",
        "watchdog.observers",
        "watchdog.events",
        "pydantic",
        "loguru",
        "PyQt6",
        "PyQt6.QtWidgets",
        "PyQt6.QtCore",
        "PyQt6.QtGui",
        "winreg",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "scipy", "PIL", "cv2"],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="WCT",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,       # no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
